// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAuditLog = `-- name: CreateAuditLog :exec
INSERT INTO audit_logs (actor_id, action, entity, entity_id, summary)
VALUES ($1, $2, $3, $4, $5)
`

type CreateAuditLogParams struct {
	ActorID  int64  `json:"actor_id"`
	Action   string `json:"action"`
	Entity   string `json:"entity"`
	EntityID int64  `json:"entity_id"`
	Summary  string `json:"summary"`
}

func (q *Queries) CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) error {
	_, err := q.db.Exec(ctx, createAuditLog,
		arg.ActorID,
		arg.Action,
		arg.Entity,
		arg.EntityID,
		arg.Summary,
	)
	return err
}

const listAuditLogs = `-- name: ListAuditLogs :many
SELECT al.id, al.actor_id, al.action, al.entity, al.entity_id, al.summary, al.created_at,
       u.name AS actor_name
FROM audit_logs al
JOIN users u ON al.actor_id = u.id
ORDER BY al.created_at DESC
LIMIT 100
`

type ListAuditLogsRow struct {
	ID        int64              `json:"id"`
	ActorID   int64              `json:"actor_id"`
	Action    string             `json:"action"`
	Entity    string             `json:"entity"`
	EntityID  int64              `json:"entity_id"`
	Summary   string             `json:"summary"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	ActorName string             `json:"actor_name"`
}

func (q *Queries) ListAuditLogs(ctx context.Context) ([]ListAuditLogsRow, error) {
	rows, err := q.db.Query(ctx, listAuditLogs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAuditLogsRow{}
	for rows.Next() {
		var i ListAuditLogsRow
		if err := rows.Scan(
			&i.ID,
			&i.ActorID,
			&i.Action,
			&i.Entity,
			&i.EntityID,
			&i.Summary,
			&i.CreatedAt,
			&i.ActorName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditLogsByEntity = `-- name: ListAuditLogsByEntity :many
SELECT al.id, al.actor_id, al.action, al.entity, al.entity_id, al.summary, al.created_at,
       u.name AS actor_name
FROM audit_logs al
JOIN users u ON al.actor_id = u.id
WHERE al.entity = $1 AND al.entity_id = $2
ORDER BY al.created_at DESC
`

type ListAuditLogsByEntityParams struct {
	Entity   string `json:"entity"`
	EntityID int64  `json:"entity_id"`
}

type ListAuditLogsByEntityRow struct {
	ID        int64              `json:"id"`
	ActorID   int64              `json:"actor_id"`
	Action    string             `json:"action"`
	Entity    string             `json:"entity"`
	EntityID  int64              `json:"entity_id"`
	Summary   string             `json:"summary"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	ActorName string             `json:"actor_name"`
}

func (q *Queries) ListAuditLogsByEntity(ctx context.Context, arg ListAuditLogsByEntityParams) ([]ListAuditLogsByEntityRow, error) {
	rows, err := q.db.Query(ctx, listAuditLogsByEntity, arg.Entity, arg.EntityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAuditLogsByEntityRow{}
	for rows.Next() {
		var i ListAuditLogsByEntityRow
		if err := rows.Scan(
			&i.ID,
			&i.ActorID,
			&i.Action,
			&i.Entity,
			&i.EntityID,
			&i.Summary,
			&i.CreatedAt,
			&i.ActorName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
