// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AuditLog struct {
	ID        int64              `json:"id"`
	ActorID   int64              `json:"actor_id"`
	Action    string             `json:"action"`
	Entity    string             `json:"entity"`
	EntityID  int64              `json:"entity_id"`
	Summary   string             `json:"summary"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Product struct {
	ID        int64              `json:"id"`
	Name      string             `json:"name"`
	Sku       string             `json:"sku"`
	Price     int64              `json:"price"`
	Active    bool               `json:"active"`
	CreatedBy int64              `json:"created_by"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID                 int64              `json:"id"`
	Username           string             `json:"username"`
	HashedPassword     string             `json:"hashed_password"`
	Name               string             `json:"name"`
	Phone              string             `json:"phone"`
	Role               string             `json:"role"`
	Active             bool               `json:"active"`
	MustChangePassword bool               `json:"must_change_password"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

type Visit struct {
	ID              int64              `json:"id"`
	SalesID         int64              `json:"sales_id"`
	WarungID        int64              `json:"warung_id"`
	Status          string             `json:"status"`
	CheckInLat      float64            `json:"check_in_lat"`
	CheckInLng      float64            `json:"check_in_lng"`
	CheckInAccuracy pgtype.Float8      `json:"check_in_accuracy"`
	CheckInTime     pgtype.Timestamptz `json:"check_in_time"`
	DistanceMeters  pgtype.Float8      `json:"distance_meters"`
	BusinessDate    pgtype.Date        `json:"business_date"`
	Notes           string             `json:"notes"`
	CancelledAt     pgtype.Timestamptz `json:"cancelled_at"`
	CancelledBy     pgtype.Int8        `json:"cancelled_by"`
	CancelReason    string             `json:"cancel_reason"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type VisitDepositItem struct {
	ID        int64 `json:"id"`
	VisitID   int64 `json:"visit_id"`
	ProductID int64 `json:"product_id"`
	Quantity  int32 `json:"quantity"`
}

type VisitPayment struct {
	ID      int64  `json:"id"`
	VisitID int64  `json:"visit_id"`
	Amount  int64  `json:"amount"`
	Method  string `json:"method"`
	Note    string `json:"note"`
}

type VisitReturnItem struct {
	ID        int64  `json:"id"`
	VisitID   int64  `json:"visit_id"`
	ProductID int64  `json:"product_id"`
	Quantity  int32  `json:"quantity"`
	Reason    string `json:"reason"`
}

type VisitSaleItem struct {
	ID        int64 `json:"id"`
	VisitID   int64 `json:"visit_id"`
	ProductID int64 `json:"product_id"`
	Quantity  int32 `json:"quantity"`
	Price     int64 `json:"price"`
}

type Warung struct {
	ID                  int64              `json:"id"`
	Name                string             `json:"name"`
	OwnerName           string             `json:"owner_name"`
	Phone               string             `json:"phone"`
	Address             string             `json:"address"`
	Latitude            pgtype.Float8      `json:"latitude"`
	Longitude           pgtype.Float8      `json:"longitude"`
	Active              bool               `json:"active"`
	CreatedBy           int64              `json:"created_by"`
	AcquiredFromCheckin bool               `json:"acquired_from_checkin"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}
