// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: products.sql

package db

import (
	"context"
)

const activeProductNameExists = `-- name: ActiveProductNameExists :one
SELECT EXISTS(
    SELECT 1 FROM products
    WHERE LOWER(name) = LOWER($1) AND active = TRUE AND ($2::bigint IS NULL OR id != $2)
)
`

type ActiveProductNameExistsParams struct {
	Lower   string `json:"lower"`
	Column2 int64  `json:"column_2"`
}

func (q *Queries) ActiveProductNameExists(ctx context.Context, arg ActiveProductNameExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, activeProductNameExists, arg.Lower, arg.Column2)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const createProduct = `-- name: CreateProduct :one
INSERT INTO products (name, sku, price, created_by)
VALUES ($1, $2, $3, $4)
RETURNING id, name, sku, price, active, created_by, created_at, updated_at
`

type CreateProductParams struct {
	Name      string `json:"name"`
	Sku       string `json:"sku"`
	Price     int64  `json:"price"`
	CreatedBy int64  `json:"created_by"`
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, createProduct,
		arg.Name,
		arg.Sku,
		arg.Price,
		arg.CreatedBy,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Sku,
		&i.Price,
		&i.Active,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deactivateProduct = `-- name: DeactivateProduct :exec
UPDATE products
SET active = FALSE, updated_at = NOW()
WHERE id = $1
`

func (q *Queries) DeactivateProduct(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deactivateProduct, id)
	return err
}

const findProductByID = `-- name: FindProductByID :one
SELECT id, name, sku, price, active, created_by, created_at, updated_at
FROM products
WHERE id = $1
`

func (q *Queries) FindProductByID(ctx context.Context, id int64) (Product, error) {
	row := q.db.QueryRow(ctx, findProductByID, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Sku,
		&i.Price,
		&i.Active,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findProductBySKU = `-- name: FindProductBySKU :one
SELECT id, name, sku, price, active, created_by, created_at, updated_at
FROM products
WHERE sku = $1
`

func (q *Queries) FindProductBySKU(ctx context.Context, sku string) (Product, error) {
	row := q.db.QueryRow(ctx, findProductBySKU, sku)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Sku,
		&i.Price,
		&i.Active,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProductPrice = `-- name: GetProductPrice :one
SELECT price FROM products WHERE id = $1
`

func (q *Queries) GetProductPrice(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRow(ctx, getProductPrice, id)
	var price int64
	err := row.Scan(&price)
	return price, err
}

const listActiveProducts = `-- name: ListActiveProducts :many
SELECT id, name, sku, price, active, created_by, created_at, updated_at
FROM products
WHERE active = TRUE
ORDER BY name
`

func (q *Queries) ListActiveProducts(ctx context.Context) ([]Product, error) {
	rows, err := q.db.Query(ctx, listActiveProducts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Product{}
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Sku,
			&i.Price,
			&i.Active,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProducts = `-- name: ListProducts :many
SELECT id, name, sku, price, active, created_by, created_at, updated_at
FROM products
ORDER BY active DESC, name
`

func (q *Queries) ListProducts(ctx context.Context) ([]Product, error) {
	rows, err := q.db.Query(ctx, listProducts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Product{}
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Sku,
			&i.Price,
			&i.Active,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProduct = `-- name: UpdateProduct :exec
UPDATE products
SET name = COALESCE($2, name),
    price = COALESCE($3, price),
    updated_at = NOW()
WHERE id = $1
`

type UpdateProductParams struct {
	ID    int64  `json:"id"`
	Name  string `json:"name"`
	Price int64  `json:"price"`
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) error {
	_, err := q.db.Exec(ctx, updateProduct, arg.ID, arg.Name, arg.Price)
	return err
}
