// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	ActiveProductNameExists(ctx context.Context, arg ActiveProductNameExistsParams) (bool, error)
	AutoCancelStaleDrafts(ctx context.Context) error
	CancelVisit(ctx context.Context, arg CancelVisitParams) error
	CorrectVisit(ctx context.Context, arg CorrectVisitParams) error
	CountActiveSales(ctx context.Context) (int64, error)
	CountUsers(ctx context.Context) (int64, error)
	CountWarungs(ctx context.Context) (int64, error)
	CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) error
	CreateDepositItem(ctx context.Context, arg CreateDepositItemParams) error
	CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error)
	CreateReturnItem(ctx context.Context, arg CreateReturnItemParams) error
	CreateSaleItem(ctx context.Context, arg CreateSaleItemParams) error
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateVisit(ctx context.Context, arg CreateVisitParams) (Visit, error)
	CreateWarung(ctx context.Context, arg CreateWarungParams) (Warung, error)
	DeactivateProduct(ctx context.Context, id int64) error
	DeactivateUser(ctx context.Context, id int64) error
	DeactivateWarung(ctx context.Context, id int64) error
	DeleteDepositItems(ctx context.Context, visitID int64) error
	DeletePayment(ctx context.Context, visitID int64) error
	DeleteReturnItems(ctx context.Context, visitID int64) error
	DeleteSaleItems(ctx context.Context, visitID int64) error
	FinalizeVisit(ctx context.Context, arg FinalizeVisitParams) error
	FindActiveDraft(ctx context.Context, salesID int64) (Visit, error)
	FindDepositItems(ctx context.Context, visitID int64) ([]FindDepositItemsRow, error)
	FindDuplicateWarungs(ctx context.Context, arg FindDuplicateWarungsParams) ([]FindDuplicateWarungsRow, error)
	FindPayment(ctx context.Context, visitID int64) (VisitPayment, error)
	FindProductByID(ctx context.Context, id int64) (Product, error)
	FindProductBySKU(ctx context.Context, sku string) (Product, error)
	FindReturnItems(ctx context.Context, visitID int64) ([]FindReturnItemsRow, error)
	FindSaleItems(ctx context.Context, visitID int64) ([]FindSaleItemsRow, error)
	FindUserByID(ctx context.Context, id int64) (User, error)
	FindUserByUsername(ctx context.Context, username string) (User, error)
	FindVisitByID(ctx context.Context, id int64) (Visit, error)
	FindWarungByID(ctx context.Context, id int64) (Warung, error)
	GetDashboardMetrics(ctx context.Context) (GetDashboardMetricsRow, error)
	GetDashboardRecentActivity(ctx context.Context) ([]GetDashboardRecentActivityRow, error)
	// Stok Awal Kunjungan: stock before a specific visit's date
	GetInitialStock(ctx context.Context, arg GetInitialStockParams) ([]GetInitialStockRow, error)
	GetProductPrice(ctx context.Context, id int64) (int64, error)
	GetReturnsReport(ctx context.Context, arg GetReturnsReportParams) ([]GetReturnsReportRow, error)
	GetSalesReport(ctx context.Context, arg GetSalesReportParams) ([]GetSalesReportRow, error)
	GetSalesReportTotal(ctx context.Context, arg GetSalesReportTotalParams) (GetSalesReportTotalRow, error)
	GetSalespersonReport(ctx context.Context, arg GetSalespersonReportParams) ([]GetSalespersonReportRow, error)
	GetWarungReport(ctx context.Context, arg GetWarungReportParams) ([]GetWarungReportRow, error)
	// Stok Titipan = total titipan - total penjualan - total retur per produk per warung
	GetWarungStock(ctx context.Context, warungID int64) ([]GetWarungStockRow, error)
	GetWarungSummary(ctx context.Context, warungID int64) (GetWarungSummaryRow, error)
	// Summary per product for a warung
	GetWarungSummaryPerProduct(ctx context.Context, warungID int64) ([]GetWarungSummaryPerProductRow, error)
	ListActiveProducts(ctx context.Context) ([]Product, error)
	ListActiveSales(ctx context.Context) ([]ListActiveSalesRow, error)
	ListActiveWarungs(ctx context.Context) ([]Warung, error)
	ListAuditLogs(ctx context.Context) ([]ListAuditLogsRow, error)
	ListAuditLogsByEntity(ctx context.Context, arg ListAuditLogsByEntityParams) ([]ListAuditLogsByEntityRow, error)
	ListProducts(ctx context.Context) ([]Product, error)
	ListRecentVisits(ctx context.Context) ([]ListRecentVisitsRow, error)
	ListSales(ctx context.Context) ([]ListSalesRow, error)
	ListVisitsBySales(ctx context.Context, salesID int64) ([]Visit, error)
	ListVisitsBySalesAndDate(ctx context.Context, arg ListVisitsBySalesAndDateParams) ([]Visit, error)
	ListVisitsByWarung(ctx context.Context, warungID int64) ([]Visit, error)
	ListWarungs(ctx context.Context) ([]Warung, error)
	SearchWarungs(ctx context.Context, dollar_1 pgtype.Text) ([]Warung, error)
	UpdateProduct(ctx context.Context, arg UpdateProductParams) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) error
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
	UpdateVisitDistance(ctx context.Context, arg UpdateVisitDistanceParams) error
	UpdateVisitStatus(ctx context.Context, arg UpdateVisitStatusParams) error
	UpdateWarung(ctx context.Context, arg UpdateWarungParams) error
	UpdateWarungGPS(ctx context.Context, arg UpdateWarungGPSParams) error
	UpsertPayment(ctx context.Context, arg UpsertPaymentParams) error
	UserExistsByUsername(ctx context.Context, lower string) (bool, error)
}

var _ Querier = (*Queries)(nil)
