// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reports.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getDashboardMetrics = `-- name: GetDashboardMetrics :one
SELECT
    (SELECT COUNT(*)::bigint FROM warungs WHERE active = TRUE) AS total_warung,
    (SELECT COUNT(*)::bigint FROM users WHERE role = 'sales' AND active = TRUE) AS total_sales,
    COALESCE((SELECT SUM(vsi.quantity)::bigint
     FROM visit_sale_items vsi
     JOIN visits v ON vsi.visit_id = v.id
     WHERE v.status = 'selesai' AND v.business_date = (CURRENT_DATE AT TIME ZONE 'Asia/Jakarta')), 0) AS pcs_sold_today,
    COALESCE((SELECT SUM(vri.quantity)::bigint
     FROM visit_return_items vri
     JOIN visits v ON vri.visit_id = v.id
     WHERE v.status = 'selesai' AND v.business_date = (CURRENT_DATE AT TIME ZONE 'Asia/Jakarta')), 0) AS pcs_returned_today,
    COALESCE((SELECT SUM(vp.amount)::bigint
     FROM visit_payments vp
     JOIN visits v ON vp.visit_id = v.id
     WHERE v.status = 'selesai' AND v.business_date = (CURRENT_DATE AT TIME ZONE 'Asia/Jakarta')), 0) AS total_pemasukan_today
`

type GetDashboardMetricsRow struct {
	TotalWarung         int64       `json:"total_warung"`
	TotalSales          int64       `json:"total_sales"`
	PcsSoldToday        interface{} `json:"pcs_sold_today"`
	PcsReturnedToday    interface{} `json:"pcs_returned_today"`
	TotalPemasukanToday interface{} `json:"total_pemasukan_today"`
}

func (q *Queries) GetDashboardMetrics(ctx context.Context) (GetDashboardMetricsRow, error) {
	row := q.db.QueryRow(ctx, getDashboardMetrics)
	var i GetDashboardMetricsRow
	err := row.Scan(
		&i.TotalWarung,
		&i.TotalSales,
		&i.PcsSoldToday,
		&i.PcsReturnedToday,
		&i.TotalPemasukanToday,
	)
	return i, err
}

const getDashboardRecentActivity = `-- name: GetDashboardRecentActivity :many
SELECT v.id, v.check_in_time, v.distance_meters, v.status, v.notes,
       u.name AS sales_name,
       w.name AS warung_name,
       COALESCE(payment.total, 0)::bigint AS pembayaran,
       COALESCE(sales.nilai, 0)::bigint AS nilai_penjualan
FROM visits v
JOIN users u ON v.sales_id = u.id
JOIN warungs w ON v.warung_id = w.id
LEFT JOIN (
    SELECT vp.visit_id, vp.amount AS total
    FROM visit_payments vp
) payment ON v.id = payment.visit_id
LEFT JOIN (
    SELECT vsi.visit_id, SUM(vsi.quantity * vsi.price) AS nilai
    FROM visit_sale_items vsi
    GROUP BY vsi.visit_id
) sales ON v.id = sales.visit_id
WHERE v.business_date = (CURRENT_DATE AT TIME ZONE 'Asia/Jakarta')
ORDER BY v.check_in_time DESC
LIMIT 20
`

type GetDashboardRecentActivityRow struct {
	ID             int64              `json:"id"`
	CheckInTime    pgtype.Timestamptz `json:"check_in_time"`
	DistanceMeters pgtype.Float8      `json:"distance_meters"`
	Status         string             `json:"status"`
	Notes          string             `json:"notes"`
	SalesName      string             `json:"sales_name"`
	WarungName     string             `json:"warung_name"`
	Pembayaran     int64              `json:"pembayaran"`
	NilaiPenjualan int64              `json:"nilai_penjualan"`
}

func (q *Queries) GetDashboardRecentActivity(ctx context.Context) ([]GetDashboardRecentActivityRow, error) {
	rows, err := q.db.Query(ctx, getDashboardRecentActivity)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetDashboardRecentActivityRow{}
	for rows.Next() {
		var i GetDashboardRecentActivityRow
		if err := rows.Scan(
			&i.ID,
			&i.CheckInTime,
			&i.DistanceMeters,
			&i.Status,
			&i.Notes,
			&i.SalesName,
			&i.WarungName,
			&i.Pembayaran,
			&i.NilaiPenjualan,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getReturnsReport = `-- name: GetReturnsReport :many
SELECT
    v.business_date,
    u.id AS sales_id,
    u.name AS sales_name,
    w.id AS warung_id,
    w.name AS warung_name,
    p.id AS product_id,
    p.name AS product_name,
    vri.quantity,
    vri.reason
FROM visit_return_items vri
JOIN visits v ON vri.visit_id = v.id
JOIN users u ON v.sales_id = u.id
JOIN warungs w ON v.warung_id = w.id
JOIN products p ON vri.product_id = p.id
WHERE v.status = 'selesai'
  AND v.business_date >= $1 AND v.business_date <= $2
  AND ($3::bigint = 0 OR p.id = $3)
  AND ($4::bigint = 0 OR w.id = $4)
  AND ($5::bigint = 0 OR u.id = $5)
ORDER BY v.business_date, u.name, w.name, p.name
`

type GetReturnsReportParams struct {
	BusinessDate   pgtype.Date `json:"business_date"`
	BusinessDate_2 pgtype.Date `json:"business_date_2"`
	Column3        int64       `json:"column_3"`
	Column4        int64       `json:"column_4"`
	Column5        int64       `json:"column_5"`
}

type GetReturnsReportRow struct {
	BusinessDate pgtype.Date `json:"business_date"`
	SalesID      int64       `json:"sales_id"`
	SalesName    string      `json:"sales_name"`
	WarungID     int64       `json:"warung_id"`
	WarungName   string      `json:"warung_name"`
	ProductID    int64       `json:"product_id"`
	ProductName  string      `json:"product_name"`
	Quantity     int32       `json:"quantity"`
	Reason       string      `json:"reason"`
}

func (q *Queries) GetReturnsReport(ctx context.Context, arg GetReturnsReportParams) ([]GetReturnsReportRow, error) {
	rows, err := q.db.Query(ctx, getReturnsReport,
		arg.BusinessDate,
		arg.BusinessDate_2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetReturnsReportRow{}
	for rows.Next() {
		var i GetReturnsReportRow
		if err := rows.Scan(
			&i.BusinessDate,
			&i.SalesID,
			&i.SalesName,
			&i.WarungID,
			&i.WarungName,
			&i.ProductID,
			&i.ProductName,
			&i.Quantity,
			&i.Reason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSalesReport = `-- name: GetSalesReport :many
SELECT
    v.business_date,
    u.id AS sales_id,
    u.name AS sales_name,
    w.id AS warung_id,
    w.name AS warung_name,
    p.id AS product_id,
    p.name AS product_name,
    p.sku AS product_sku,
    vsi.quantity,
    vsi.price,
    (vsi.quantity * vsi.price)::bigint AS nilai
FROM visit_sale_items vsi
JOIN visits v ON vsi.visit_id = v.id
JOIN users u ON v.sales_id = u.id
JOIN warungs w ON v.warung_id = w.id
JOIN products p ON vsi.product_id = p.id
WHERE v.status = 'selesai'
  AND v.business_date >= $1 AND v.business_date <= $2
ORDER BY v.business_date, u.name, w.name, p.name
`

type GetSalesReportParams struct {
	BusinessDate   pgtype.Date `json:"business_date"`
	BusinessDate_2 pgtype.Date `json:"business_date_2"`
}

type GetSalesReportRow struct {
	BusinessDate pgtype.Date `json:"business_date"`
	SalesID      int64       `json:"sales_id"`
	SalesName    string      `json:"sales_name"`
	WarungID     int64       `json:"warung_id"`
	WarungName   string      `json:"warung_name"`
	ProductID    int64       `json:"product_id"`
	ProductName  string      `json:"product_name"`
	ProductSku   string      `json:"product_sku"`
	Quantity     int32       `json:"quantity"`
	Price        int64       `json:"price"`
	Nilai        int64       `json:"nilai"`
}

func (q *Queries) GetSalesReport(ctx context.Context, arg GetSalesReportParams) ([]GetSalesReportRow, error) {
	rows, err := q.db.Query(ctx, getSalesReport, arg.BusinessDate, arg.BusinessDate_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetSalesReportRow{}
	for rows.Next() {
		var i GetSalesReportRow
		if err := rows.Scan(
			&i.BusinessDate,
			&i.SalesID,
			&i.SalesName,
			&i.WarungID,
			&i.WarungName,
			&i.ProductID,
			&i.ProductName,
			&i.ProductSku,
			&i.Quantity,
			&i.Price,
			&i.Nilai,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSalesReportTotal = `-- name: GetSalesReportTotal :one
SELECT
    COALESCE(SUM(vsi.quantity), 0)::bigint AS total_pcs,
    COALESCE(SUM(vsi.quantity * vsi.price), 0)::bigint AS total_nilai
FROM visit_sale_items vsi
JOIN visits v ON vsi.visit_id = v.id
WHERE v.status = 'selesai'
  AND v.business_date >= $1 AND v.business_date <= $2
`

type GetSalesReportTotalParams struct {
	BusinessDate   pgtype.Date `json:"business_date"`
	BusinessDate_2 pgtype.Date `json:"business_date_2"`
}

type GetSalesReportTotalRow struct {
	TotalPcs   int64 `json:"total_pcs"`
	TotalNilai int64 `json:"total_nilai"`
}

func (q *Queries) GetSalesReportTotal(ctx context.Context, arg GetSalesReportTotalParams) (GetSalesReportTotalRow, error) {
	row := q.db.QueryRow(ctx, getSalesReportTotal, arg.BusinessDate, arg.BusinessDate_2)
	var i GetSalesReportTotalRow
	err := row.Scan(&i.TotalPcs, &i.TotalNilai)
	return i, err
}

const getSalespersonReport = `-- name: GetSalespersonReport :many
SELECT
    u.id AS sales_id,
    u.name AS sales_name,
    COUNT(v.id)::bigint AS total_kunjungan,
    COUNT(v.id) FILTER (WHERE EXISTS (
        SELECT 1 FROM visit_deposit_items WHERE visit_id = v.id
        UNION ALL
        SELECT 1 FROM visit_sale_items WHERE visit_id = v.id
        UNION ALL
        SELECT 1 FROM visit_return_items WHERE visit_id = v.id
        UNION ALL
        SELECT 1 FROM visit_payments WHERE visit_id = v.id
    ))::bigint AS kunjungan_dengan_transaksi,
    COALESCE(SUM(sales.quantity), 0)::bigint AS produk_terjual,
    COALESCE(SUM(sales.nilai), 0)::bigint AS nilai_penjualan,
    COALESCE(SUM(payments.amount), 0)::bigint AS pembayaran,
    COALESCE(SUM(retur.quantity), 0)::bigint AS retur
FROM users u
LEFT JOIN visits v ON u.id = v.sales_id AND v.status = 'selesai' AND v.business_date >= $1 AND v.business_date <= $2
LEFT JOIN (
    SELECT vsi.visit_id, SUM(vsi.quantity)::bigint AS quantity, SUM(vsi.quantity * vsi.price)::bigint AS nilai
    FROM visit_sale_items vsi
    GROUP BY vsi.visit_id
) sales ON v.id = sales.visit_id
LEFT JOIN visit_payments payments ON v.id = payments.visit_id
LEFT JOIN (
    SELECT visit_id, SUM(quantity)::bigint AS quantity
    FROM visit_return_items
    GROUP BY visit_id
) retur ON v.id = retur.visit_id
GROUP BY u.id, u.name
HAVING u.role = 'sales' AND COUNT(v.id) > 0
ORDER BY u.name
`

type GetSalespersonReportParams struct {
	BusinessDate   pgtype.Date `json:"business_date"`
	BusinessDate_2 pgtype.Date `json:"business_date_2"`
}

type GetSalespersonReportRow struct {
	SalesID                  int64  `json:"sales_id"`
	SalesName                string `json:"sales_name"`
	TotalKunjungan           int64  `json:"total_kunjungan"`
	KunjunganDenganTransaksi int64  `json:"kunjungan_dengan_transaksi"`
	ProdukTerjual            int64  `json:"produk_terjual"`
	NilaiPenjualan           int64  `json:"nilai_penjualan"`
	Pembayaran               int64  `json:"pembayaran"`
	Retur                    int64  `json:"retur"`
}

func (q *Queries) GetSalespersonReport(ctx context.Context, arg GetSalespersonReportParams) ([]GetSalespersonReportRow, error) {
	rows, err := q.db.Query(ctx, getSalespersonReport, arg.BusinessDate, arg.BusinessDate_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetSalespersonReportRow{}
	for rows.Next() {
		var i GetSalespersonReportRow
		if err := rows.Scan(
			&i.SalesID,
			&i.SalesName,
			&i.TotalKunjungan,
			&i.KunjunganDenganTransaksi,
			&i.ProdukTerjual,
			&i.NilaiPenjualan,
			&i.Pembayaran,
			&i.Retur,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWarungReport = `-- name: GetWarungReport :many
SELECT
    w.id AS warung_id,
    w.name AS warung_name,
    COALESCE(SUM(deposits.quantity), 0)::bigint AS total_titipan,
    COALESCE(SUM(sales.quantity), 0)::bigint AS total_terjual,
    COALESCE(SUM(retur.quantity), 0)::bigint AS total_retur,
    COALESCE(SUM(sales.nilai), 0)::bigint AS nilai_penjualan,
    COALESCE(SUM(payments.amount), 0)::bigint AS pembayaran
FROM warungs w
LEFT JOIN visits v ON w.id = v.warung_id AND v.status = 'selesai' AND v.business_date >= $1 AND v.business_date <= $2
LEFT JOIN (
    SELECT visit_id, SUM(quantity)::bigint AS quantity
    FROM visit_deposit_items
    GROUP BY visit_id
) deposits ON v.id = deposits.visit_id
LEFT JOIN (
    SELECT vsi.visit_id, SUM(vsi.quantity)::bigint AS quantity, SUM(vsi.quantity * vsi.price)::bigint AS nilai
    FROM visit_sale_items vsi
    GROUP BY vsi.visit_id
) sales ON v.id = sales.visit_id
LEFT JOIN (
    SELECT visit_id, SUM(quantity)::bigint AS quantity
    FROM visit_return_items
    GROUP BY visit_id
) retur ON v.id = retur.visit_id
LEFT JOIN visit_payments payments ON v.id = payments.visit_id
WHERE v.id IS NOT NULL
GROUP BY w.id, w.name
ORDER BY w.name
`

type GetWarungReportParams struct {
	BusinessDate   pgtype.Date `json:"business_date"`
	BusinessDate_2 pgtype.Date `json:"business_date_2"`
}

type GetWarungReportRow struct {
	WarungID       int64  `json:"warung_id"`
	WarungName     string `json:"warung_name"`
	TotalTitipan   int64  `json:"total_titipan"`
	TotalTerjual   int64  `json:"total_terjual"`
	TotalRetur     int64  `json:"total_retur"`
	NilaiPenjualan int64  `json:"nilai_penjualan"`
	Pembayaran     int64  `json:"pembayaran"`
}

func (q *Queries) GetWarungReport(ctx context.Context, arg GetWarungReportParams) ([]GetWarungReportRow, error) {
	rows, err := q.db.Query(ctx, getWarungReport, arg.BusinessDate, arg.BusinessDate_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetWarungReportRow{}
	for rows.Next() {
		var i GetWarungReportRow
		if err := rows.Scan(
			&i.WarungID,
			&i.WarungName,
			&i.TotalTitipan,
			&i.TotalTerjual,
			&i.TotalRetur,
			&i.NilaiPenjualan,
			&i.Pembayaran,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
