// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: stock.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getInitialStock = `-- name: GetInitialStock :many
SELECT
    p.id AS product_id,
    p.name AS product_name,
    COALESCE(SUM(deposits.quantity), 0) - COALESCE(SUM(sales.quantity), 0) - COALESCE(SUM(returns.quantity), 0) AS stock
FROM products p
LEFT JOIN (
    SELECT vdi.product_id, SUM(vdi.quantity)::int AS quantity
    FROM visit_deposit_items vdi
    JOIN visits v ON vdi.visit_id = v.id
    WHERE v.warung_id = $1 AND v.status = 'selesai' AND v.business_date < $2
    GROUP BY vdi.product_id
) deposits ON p.id = deposits.product_id
LEFT JOIN (
    SELECT vsi.product_id, SUM(vsi.quantity)::int AS quantity
    FROM visit_sale_items vsi
    JOIN visits v ON vsi.visit_id = v.id
    WHERE v.warung_id = $1 AND v.status = 'selesai' AND v.business_date < $2
    GROUP BY vsi.product_id
) sales ON p.id = sales.product_id
LEFT JOIN (
    SELECT vri.product_id, SUM(vri.quantity)::int AS quantity
    FROM visit_return_items vri
    JOIN visits v ON vri.visit_id = v.id
    WHERE v.warung_id = $1 AND v.status = 'selesai' AND v.business_date < $2
    GROUP BY vri.product_id
) returns ON p.id = returns.product_id
WHERE (deposits.product_id IS NOT NULL OR sales.product_id IS NOT NULL OR returns.product_id IS NOT NULL)
  AND COALESCE(SUM(deposits.quantity), 0) - COALESCE(SUM(sales.quantity), 0) - COALESCE(SUM(returns.quantity), 0) > 0
GROUP BY p.id, p.name
ORDER BY p.name
`

type GetInitialStockParams struct {
	WarungID     int64       `json:"warung_id"`
	BusinessDate pgtype.Date `json:"business_date"`
}

type GetInitialStockRow struct {
	ProductID   int64  `json:"product_id"`
	ProductName string `json:"product_name"`
	Stock       int32  `json:"stock"`
}

// Stok Awal Kunjungan: stock before a specific visit's date
func (q *Queries) GetInitialStock(ctx context.Context, arg GetInitialStockParams) ([]GetInitialStockRow, error) {
	rows, err := q.db.Query(ctx, getInitialStock, arg.WarungID, arg.BusinessDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetInitialStockRow{}
	for rows.Next() {
		var i GetInitialStockRow
		if err := rows.Scan(&i.ProductID, &i.ProductName, &i.Stock); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWarungStock = `-- name: GetWarungStock :many
SELECT
    p.id AS product_id,
    p.name AS product_name,
    p.sku AS product_sku,
    COALESCE(SUM(deposits.quantity), 0) - COALESCE(SUM(sales.quantity), 0) - COALESCE(SUM(returns.quantity), 0) AS stock
FROM products p
LEFT JOIN (
    SELECT vdi.product_id, SUM(vdi.quantity)::int AS quantity
    FROM visit_deposit_items vdi
    JOIN visits v ON vdi.visit_id = v.id
    WHERE v.warung_id = $1 AND v.status = 'selesai'
    GROUP BY vdi.product_id
) deposits ON p.id = deposits.product_id
LEFT JOIN (
    SELECT vsi.product_id, SUM(vsi.quantity)::int AS quantity
    FROM visit_sale_items vsi
    JOIN visits v ON vsi.visit_id = v.id
    WHERE v.warung_id = $1 AND v.status = 'selesai'
    GROUP BY vsi.product_id
) sales ON p.id = sales.product_id
LEFT JOIN (
    SELECT vri.product_id, SUM(vri.quantity)::int AS quantity
    FROM visit_return_items vri
    JOIN visits v ON vri.visit_id = v.id
    WHERE v.warung_id = $1 AND v.status = 'selesai'
    GROUP BY vri.product_id
) returns ON p.id = returns.product_id
WHERE (deposits.product_id IS NOT NULL OR sales.product_id IS NOT NULL OR returns.product_id IS NOT NULL)
  AND COALESCE(SUM(deposits.quantity), 0) - COALESCE(SUM(sales.quantity), 0) - COALESCE(SUM(returns.quantity), 0) > 0
GROUP BY p.id, p.name, p.sku
ORDER BY p.name
`

type GetWarungStockRow struct {
	ProductID   int64  `json:"product_id"`
	ProductName string `json:"product_name"`
	ProductSku  string `json:"product_sku"`
	Stock       int32  `json:"stock"`
}

// Stok Titipan = total titipan - total penjualan - total retur per produk per warung
func (q *Queries) GetWarungStock(ctx context.Context, warungID int64) ([]GetWarungStockRow, error) {
	rows, err := q.db.Query(ctx, getWarungStock, warungID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetWarungStockRow{}
	for rows.Next() {
		var i GetWarungStockRow
		if err := rows.Scan(
			&i.ProductID,
			&i.ProductName,
			&i.ProductSku,
			&i.Stock,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWarungSummary = `-- name: GetWarungSummary :one
SELECT
    COALESCE(SUM(vp.amount), 0)::bigint AS total_pembayaran,
    COALESCE(SUM(vsi.quantity * vsi.price), 0)::bigint AS total_nilai_penjualan
FROM visits v
LEFT JOIN visit_payments vp ON v.id = vp.visit_id
LEFT JOIN (
    SELECT vsi2.visit_id, SUM(vsi2.quantity * vsi2.price) AS total_per_visit
    FROM visit_sale_items vsi2
    GROUP BY vsi2.visit_id
) vsi ON v.id = vsi.visit_id
WHERE v.warung_id = $1 AND v.status = 'selesai'
`

type GetWarungSummaryRow struct {
	TotalPembayaran     int64 `json:"total_pembayaran"`
	TotalNilaiPenjualan int64 `json:"total_nilai_penjualan"`
}

func (q *Queries) GetWarungSummary(ctx context.Context, warungID int64) (GetWarungSummaryRow, error) {
	row := q.db.QueryRow(ctx, getWarungSummary, warungID)
	var i GetWarungSummaryRow
	err := row.Scan(&i.TotalPembayaran, &i.TotalNilaiPenjualan)
	return i, err
}

const getWarungSummaryPerProduct = `-- name: GetWarungSummaryPerProduct :many
SELECT
    p.id AS product_id,
    p.name AS product_name,
    p.sku AS product_sku,
    COALESCE(SUM(deposits.quantity), 0)::int AS total_titipan,
    COALESCE(SUM(sales.quantity), 0)::int AS total_terjual,
    COALESCE(SUM(returns.quantity), 0)::int AS total_retur,
    COALESCE(SUM(deposits.quantity), 0)::int - COALESCE(SUM(sales.quantity), 0)::int - COALESCE(SUM(returns.quantity), 0)::int AS stock,
    COALESCE(SUM(sales.quantity * sales.price), 0)::bigint AS nilai_penjualan
FROM products p
LEFT JOIN (
    SELECT vdi.product_id, SUM(vdi.quantity)::int AS quantity
    FROM visit_deposit_items vdi
    JOIN visits v ON vdi.visit_id = v.id
    WHERE v.warung_id = $1 AND v.status = 'selesai'
    GROUP BY vdi.product_id
) deposits ON p.id = deposits.product_id
LEFT JOIN (
    SELECT vsi.product_id, SUM(vsi.quantity)::int AS quantity, vsi.price
    FROM visit_sale_items vsi
    JOIN visits v ON vsi.visit_id = v.id
    WHERE v.warung_id = $1 AND v.status = 'selesai'
    GROUP BY vsi.product_id, vsi.price
) sales ON p.id = sales.product_id
LEFT JOIN (
    SELECT vri.product_id, SUM(vri.quantity)::int AS quantity
    FROM visit_return_items vri
    JOIN visits v ON vri.visit_id = v.id
    WHERE v.warung_id = $1 AND v.status = 'selesai'
    GROUP BY vri.product_id
) returns ON p.id = returns.product_id
WHERE (deposits.product_id IS NOT NULL OR sales.product_id IS NOT NULL OR returns.product_id IS NOT NULL)
GROUP BY p.id, p.name, p.sku
ORDER BY p.name
`

type GetWarungSummaryPerProductRow struct {
	ProductID      int64  `json:"product_id"`
	ProductName    string `json:"product_name"`
	ProductSku     string `json:"product_sku"`
	TotalTitipan   int32  `json:"total_titipan"`
	TotalTerjual   int32  `json:"total_terjual"`
	TotalRetur     int32  `json:"total_retur"`
	Stock          int32  `json:"stock"`
	NilaiPenjualan int64  `json:"nilai_penjualan"`
}

// Summary per product for a warung
func (q *Queries) GetWarungSummaryPerProduct(ctx context.Context, warungID int64) ([]GetWarungSummaryPerProductRow, error) {
	rows, err := q.db.Query(ctx, getWarungSummaryPerProduct, warungID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetWarungSummaryPerProductRow{}
	for rows.Next() {
		var i GetWarungSummaryPerProductRow
		if err := rows.Scan(
			&i.ProductID,
			&i.ProductName,
			&i.ProductSku,
			&i.TotalTitipan,
			&i.TotalTerjual,
			&i.TotalRetur,
			&i.Stock,
			&i.NilaiPenjualan,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
