// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countActiveSales = `-- name: CountActiveSales :one
SELECT COUNT(*)::bigint FROM users WHERE role = 'sales' AND active = TRUE
`

func (q *Queries) CountActiveSales(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveSales)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*)::bigint FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (username, hashed_password, name, phone, role, must_change_password)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, username, hashed_password, name, phone, role, active, must_change_password, created_at, updated_at
`

type CreateUserParams struct {
	Username           string `json:"username"`
	HashedPassword     string `json:"hashed_password"`
	Name               string `json:"name"`
	Phone              string `json:"phone"`
	Role               string `json:"role"`
	MustChangePassword bool   `json:"must_change_password"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Username,
		arg.HashedPassword,
		arg.Name,
		arg.Phone,
		arg.Role,
		arg.MustChangePassword,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.HashedPassword,
		&i.Name,
		&i.Phone,
		&i.Role,
		&i.Active,
		&i.MustChangePassword,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deactivateUser = `-- name: DeactivateUser :exec
UPDATE users
SET active = FALSE, updated_at = NOW()
WHERE id = $1
`

func (q *Queries) DeactivateUser(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deactivateUser, id)
	return err
}

const findUserByID = `-- name: FindUserByID :one
SELECT id, username, hashed_password, name, phone, role, active, must_change_password, created_at, updated_at
FROM users
WHERE id = $1
`

func (q *Queries) FindUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, findUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.HashedPassword,
		&i.Name,
		&i.Phone,
		&i.Role,
		&i.Active,
		&i.MustChangePassword,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findUserByUsername = `-- name: FindUserByUsername :one
SELECT id, username, hashed_password, name, phone, role, active, must_change_password, created_at, updated_at
FROM users
WHERE LOWER(username) = LOWER($1)
`

func (q *Queries) FindUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, findUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.HashedPassword,
		&i.Name,
		&i.Phone,
		&i.Role,
		&i.Active,
		&i.MustChangePassword,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveSales = `-- name: ListActiveSales :many
SELECT id, username, name, phone, role, active, must_change_password, created_at, updated_at
FROM users
WHERE role = 'sales' AND active = TRUE
ORDER BY name
`

type ListActiveSalesRow struct {
	ID                 int64              `json:"id"`
	Username           string             `json:"username"`
	Name               string             `json:"name"`
	Phone              string             `json:"phone"`
	Role               string             `json:"role"`
	Active             bool               `json:"active"`
	MustChangePassword bool               `json:"must_change_password"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListActiveSales(ctx context.Context) ([]ListActiveSalesRow, error) {
	rows, err := q.db.Query(ctx, listActiveSales)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveSalesRow{}
	for rows.Next() {
		var i ListActiveSalesRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Name,
			&i.Phone,
			&i.Role,
			&i.Active,
			&i.MustChangePassword,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSales = `-- name: ListSales :many
SELECT id, username, name, phone, role, active, must_change_password, created_at, updated_at
FROM users
WHERE role = 'sales'
ORDER BY created_at DESC
`

type ListSalesRow struct {
	ID                 int64              `json:"id"`
	Username           string             `json:"username"`
	Name               string             `json:"name"`
	Phone              string             `json:"phone"`
	Role               string             `json:"role"`
	Active             bool               `json:"active"`
	MustChangePassword bool               `json:"must_change_password"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListSales(ctx context.Context) ([]ListSalesRow, error) {
	rows, err := q.db.Query(ctx, listSales)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSalesRow{}
	for rows.Next() {
		var i ListSalesRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Name,
			&i.Phone,
			&i.Role,
			&i.Active,
			&i.MustChangePassword,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :exec
UPDATE users
SET name = COALESCE($2, name),
    phone = COALESCE($3, phone),
    updated_at = NOW()
WHERE id = $1
`

type UpdateUserParams struct {
	ID    int64  `json:"id"`
	Name  string `json:"name"`
	Phone string `json:"phone"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.Exec(ctx, updateUser, arg.ID, arg.Name, arg.Phone)
	return err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users
SET hashed_password = $2, must_change_password = $3, updated_at = NOW()
WHERE id = $1
`

type UpdateUserPasswordParams struct {
	ID                 int64  `json:"id"`
	HashedPassword     string `json:"hashed_password"`
	MustChangePassword bool   `json:"must_change_password"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.Exec(ctx, updateUserPassword, arg.ID, arg.HashedPassword, arg.MustChangePassword)
	return err
}

const userExistsByUsername = `-- name: UserExistsByUsername :one
SELECT EXISTS(SELECT 1 FROM users WHERE LOWER(username) = LOWER($1))
`

func (q *Queries) UserExistsByUsername(ctx context.Context, lower string) (bool, error) {
	row := q.db.QueryRow(ctx, userExistsByUsername, lower)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
