// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: visit_items.sql

package db

import (
	"context"
)

const createDepositItem = `-- name: CreateDepositItem :exec
INSERT INTO visit_deposit_items (visit_id, product_id, quantity)
VALUES ($1, $2, $3)
ON CONFLICT (visit_id, product_id) DO UPDATE SET quantity = $3
`

type CreateDepositItemParams struct {
	VisitID   int64 `json:"visit_id"`
	ProductID int64 `json:"product_id"`
	Quantity  int32 `json:"quantity"`
}

func (q *Queries) CreateDepositItem(ctx context.Context, arg CreateDepositItemParams) error {
	_, err := q.db.Exec(ctx, createDepositItem, arg.VisitID, arg.ProductID, arg.Quantity)
	return err
}

const createReturnItem = `-- name: CreateReturnItem :exec
INSERT INTO visit_return_items (visit_id, product_id, quantity, reason)
VALUES ($1, $2, $3, $4)
ON CONFLICT (visit_id, product_id) DO UPDATE SET quantity = $3, reason = $4
`

type CreateReturnItemParams struct {
	VisitID   int64  `json:"visit_id"`
	ProductID int64  `json:"product_id"`
	Quantity  int32  `json:"quantity"`
	Reason    string `json:"reason"`
}

func (q *Queries) CreateReturnItem(ctx context.Context, arg CreateReturnItemParams) error {
	_, err := q.db.Exec(ctx, createReturnItem,
		arg.VisitID,
		arg.ProductID,
		arg.Quantity,
		arg.Reason,
	)
	return err
}

const createSaleItem = `-- name: CreateSaleItem :exec
INSERT INTO visit_sale_items (visit_id, product_id, quantity, price)
VALUES ($1, $2, $3, $4)
ON CONFLICT (visit_id, product_id) DO UPDATE SET quantity = $3, price = $4
`

type CreateSaleItemParams struct {
	VisitID   int64 `json:"visit_id"`
	ProductID int64 `json:"product_id"`
	Quantity  int32 `json:"quantity"`
	Price     int64 `json:"price"`
}

func (q *Queries) CreateSaleItem(ctx context.Context, arg CreateSaleItemParams) error {
	_, err := q.db.Exec(ctx, createSaleItem,
		arg.VisitID,
		arg.ProductID,
		arg.Quantity,
		arg.Price,
	)
	return err
}

const deleteDepositItems = `-- name: DeleteDepositItems :exec
DELETE FROM visit_deposit_items WHERE visit_id = $1
`

func (q *Queries) DeleteDepositItems(ctx context.Context, visitID int64) error {
	_, err := q.db.Exec(ctx, deleteDepositItems, visitID)
	return err
}

const deletePayment = `-- name: DeletePayment :exec
DELETE FROM visit_payments WHERE visit_id = $1
`

func (q *Queries) DeletePayment(ctx context.Context, visitID int64) error {
	_, err := q.db.Exec(ctx, deletePayment, visitID)
	return err
}

const deleteReturnItems = `-- name: DeleteReturnItems :exec
DELETE FROM visit_return_items WHERE visit_id = $1
`

func (q *Queries) DeleteReturnItems(ctx context.Context, visitID int64) error {
	_, err := q.db.Exec(ctx, deleteReturnItems, visitID)
	return err
}

const deleteSaleItems = `-- name: DeleteSaleItems :exec
DELETE FROM visit_sale_items WHERE visit_id = $1
`

func (q *Queries) DeleteSaleItems(ctx context.Context, visitID int64) error {
	_, err := q.db.Exec(ctx, deleteSaleItems, visitID)
	return err
}

const findDepositItems = `-- name: FindDepositItems :many
SELECT vdi.id, vdi.visit_id, vdi.product_id, vdi.quantity, p.name AS product_name
FROM visit_deposit_items vdi
JOIN products p ON vdi.product_id = p.id
WHERE vdi.visit_id = $1
ORDER BY p.name
`

type FindDepositItemsRow struct {
	ID          int64  `json:"id"`
	VisitID     int64  `json:"visit_id"`
	ProductID   int64  `json:"product_id"`
	Quantity    int32  `json:"quantity"`
	ProductName string `json:"product_name"`
}

func (q *Queries) FindDepositItems(ctx context.Context, visitID int64) ([]FindDepositItemsRow, error) {
	rows, err := q.db.Query(ctx, findDepositItems, visitID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindDepositItemsRow{}
	for rows.Next() {
		var i FindDepositItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.VisitID,
			&i.ProductID,
			&i.Quantity,
			&i.ProductName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findPayment = `-- name: FindPayment :one
SELECT id, visit_id, amount, method, note
FROM visit_payments
WHERE visit_id = $1
`

func (q *Queries) FindPayment(ctx context.Context, visitID int64) (VisitPayment, error) {
	row := q.db.QueryRow(ctx, findPayment, visitID)
	var i VisitPayment
	err := row.Scan(
		&i.ID,
		&i.VisitID,
		&i.Amount,
		&i.Method,
		&i.Note,
	)
	return i, err
}

const findReturnItems = `-- name: FindReturnItems :many
SELECT vri.id, vri.visit_id, vri.product_id, vri.quantity, vri.reason, p.name AS product_name
FROM visit_return_items vri
JOIN products p ON vri.product_id = p.id
WHERE vri.visit_id = $1
ORDER BY p.name
`

type FindReturnItemsRow struct {
	ID          int64  `json:"id"`
	VisitID     int64  `json:"visit_id"`
	ProductID   int64  `json:"product_id"`
	Quantity    int32  `json:"quantity"`
	Reason      string `json:"reason"`
	ProductName string `json:"product_name"`
}

func (q *Queries) FindReturnItems(ctx context.Context, visitID int64) ([]FindReturnItemsRow, error) {
	rows, err := q.db.Query(ctx, findReturnItems, visitID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindReturnItemsRow{}
	for rows.Next() {
		var i FindReturnItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.VisitID,
			&i.ProductID,
			&i.Quantity,
			&i.Reason,
			&i.ProductName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findSaleItems = `-- name: FindSaleItems :many
SELECT vsi.id, vsi.visit_id, vsi.product_id, vsi.quantity, vsi.price, p.name AS product_name
FROM visit_sale_items vsi
JOIN products p ON vsi.product_id = p.id
WHERE vsi.visit_id = $1
ORDER BY p.name
`

type FindSaleItemsRow struct {
	ID          int64  `json:"id"`
	VisitID     int64  `json:"visit_id"`
	ProductID   int64  `json:"product_id"`
	Quantity    int32  `json:"quantity"`
	Price       int64  `json:"price"`
	ProductName string `json:"product_name"`
}

func (q *Queries) FindSaleItems(ctx context.Context, visitID int64) ([]FindSaleItemsRow, error) {
	rows, err := q.db.Query(ctx, findSaleItems, visitID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindSaleItemsRow{}
	for rows.Next() {
		var i FindSaleItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.VisitID,
			&i.ProductID,
			&i.Quantity,
			&i.Price,
			&i.ProductName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertPayment = `-- name: UpsertPayment :exec
INSERT INTO visit_payments (visit_id, amount, method, note)
VALUES ($1, $2, $3, $4)
ON CONFLICT (visit_id) DO UPDATE SET amount = $2, method = $3, note = $4
`

type UpsertPaymentParams struct {
	VisitID int64  `json:"visit_id"`
	Amount  int64  `json:"amount"`
	Method  string `json:"method"`
	Note    string `json:"note"`
}

func (q *Queries) UpsertPayment(ctx context.Context, arg UpsertPaymentParams) error {
	_, err := q.db.Exec(ctx, upsertPayment,
		arg.VisitID,
		arg.Amount,
		arg.Method,
		arg.Note,
	)
	return err
}
