// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: visits.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const autoCancelStaleDrafts = `-- name: AutoCancelStaleDrafts :exec
UPDATE visits
SET status = 'dibatalkan', cancelled_at = NOW(), cancel_reason = 'Auto-cancelled: tidak diselesaikan sebelum akhir Hari Bisnis', updated_at = NOW()
WHERE status = 'draft' AND business_date < (CURRENT_DATE AT TIME ZONE 'Asia/Jakarta')
`

func (q *Queries) AutoCancelStaleDrafts(ctx context.Context) error {
	_, err := q.db.Exec(ctx, autoCancelStaleDrafts)
	return err
}

const cancelVisit = `-- name: CancelVisit :exec
UPDATE visits
SET status = 'dibatalkan', cancelled_at = NOW(), cancelled_by = $2, cancel_reason = $3, updated_at = NOW()
WHERE id = $1
`

type CancelVisitParams struct {
	ID           int64       `json:"id"`
	CancelledBy  pgtype.Int8 `json:"cancelled_by"`
	CancelReason string      `json:"cancel_reason"`
}

func (q *Queries) CancelVisit(ctx context.Context, arg CancelVisitParams) error {
	_, err := q.db.Exec(ctx, cancelVisit, arg.ID, arg.CancelledBy, arg.CancelReason)
	return err
}

const correctVisit = `-- name: CorrectVisit :exec
UPDATE visits
SET notes = COALESCE($2, notes), updated_at = NOW()
WHERE id = $1
`

type CorrectVisitParams struct {
	ID    int64  `json:"id"`
	Notes string `json:"notes"`
}

func (q *Queries) CorrectVisit(ctx context.Context, arg CorrectVisitParams) error {
	_, err := q.db.Exec(ctx, correctVisit, arg.ID, arg.Notes)
	return err
}

const createVisit = `-- name: CreateVisit :one
INSERT INTO visits (sales_id, warung_id, check_in_lat, check_in_lng, check_in_accuracy, check_in_time, business_date)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, sales_id, warung_id, status, check_in_lat, check_in_lng, check_in_accuracy, check_in_time, distance_meters, business_date, notes, cancelled_at, cancelled_by, cancel_reason, created_at, updated_at
`

type CreateVisitParams struct {
	SalesID         int64              `json:"sales_id"`
	WarungID        int64              `json:"warung_id"`
	CheckInLat      float64            `json:"check_in_lat"`
	CheckInLng      float64            `json:"check_in_lng"`
	CheckInAccuracy pgtype.Float8      `json:"check_in_accuracy"`
	CheckInTime     pgtype.Timestamptz `json:"check_in_time"`
	BusinessDate    pgtype.Date        `json:"business_date"`
}

func (q *Queries) CreateVisit(ctx context.Context, arg CreateVisitParams) (Visit, error) {
	row := q.db.QueryRow(ctx, createVisit,
		arg.SalesID,
		arg.WarungID,
		arg.CheckInLat,
		arg.CheckInLng,
		arg.CheckInAccuracy,
		arg.CheckInTime,
		arg.BusinessDate,
	)
	var i Visit
	err := row.Scan(
		&i.ID,
		&i.SalesID,
		&i.WarungID,
		&i.Status,
		&i.CheckInLat,
		&i.CheckInLng,
		&i.CheckInAccuracy,
		&i.CheckInTime,
		&i.DistanceMeters,
		&i.BusinessDate,
		&i.Notes,
		&i.CancelledAt,
		&i.CancelledBy,
		&i.CancelReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const finalizeVisit = `-- name: FinalizeVisit :exec
UPDATE visits
SET status = 'selesai', notes = $2, updated_at = NOW()
WHERE id = $1
`

type FinalizeVisitParams struct {
	ID    int64  `json:"id"`
	Notes string `json:"notes"`
}

func (q *Queries) FinalizeVisit(ctx context.Context, arg FinalizeVisitParams) error {
	_, err := q.db.Exec(ctx, finalizeVisit, arg.ID, arg.Notes)
	return err
}

const findActiveDraft = `-- name: FindActiveDraft :one
SELECT id, sales_id, warung_id, status, check_in_lat, check_in_lng, check_in_accuracy, check_in_time, distance_meters, business_date, notes, cancelled_at, cancelled_by, cancel_reason, created_at, updated_at
FROM visits
WHERE sales_id = $1 AND status = 'draft'
`

func (q *Queries) FindActiveDraft(ctx context.Context, salesID int64) (Visit, error) {
	row := q.db.QueryRow(ctx, findActiveDraft, salesID)
	var i Visit
	err := row.Scan(
		&i.ID,
		&i.SalesID,
		&i.WarungID,
		&i.Status,
		&i.CheckInLat,
		&i.CheckInLng,
		&i.CheckInAccuracy,
		&i.CheckInTime,
		&i.DistanceMeters,
		&i.BusinessDate,
		&i.Notes,
		&i.CancelledAt,
		&i.CancelledBy,
		&i.CancelReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findVisitByID = `-- name: FindVisitByID :one
SELECT id, sales_id, warung_id, status, check_in_lat, check_in_lng, check_in_accuracy, check_in_time, distance_meters, business_date, notes, cancelled_at, cancelled_by, cancel_reason, created_at, updated_at
FROM visits
WHERE id = $1
`

func (q *Queries) FindVisitByID(ctx context.Context, id int64) (Visit, error) {
	row := q.db.QueryRow(ctx, findVisitByID, id)
	var i Visit
	err := row.Scan(
		&i.ID,
		&i.SalesID,
		&i.WarungID,
		&i.Status,
		&i.CheckInLat,
		&i.CheckInLng,
		&i.CheckInAccuracy,
		&i.CheckInTime,
		&i.DistanceMeters,
		&i.BusinessDate,
		&i.Notes,
		&i.CancelledAt,
		&i.CancelledBy,
		&i.CancelReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listRecentVisits = `-- name: ListRecentVisits :many
SELECT v.id, v.sales_id, v.warung_id, v.status, v.check_in_lat, v.check_in_lng, v.check_in_accuracy, v.check_in_time, v.distance_meters, v.business_date, v.notes, v.cancelled_at, v.cancelled_by, v.cancel_reason, v.created_at, v.updated_at,
       u.name AS sales_name, w.name AS warung_name
FROM visits v
JOIN users u ON v.sales_id = u.id
JOIN warungs w ON v.warung_id = w.id
WHERE v.business_date = (CURRENT_DATE AT TIME ZONE 'Asia/Jakarta')
ORDER BY v.check_in_time DESC
LIMIT 20
`

type ListRecentVisitsRow struct {
	ID              int64              `json:"id"`
	SalesID         int64              `json:"sales_id"`
	WarungID        int64              `json:"warung_id"`
	Status          string             `json:"status"`
	CheckInLat      float64            `json:"check_in_lat"`
	CheckInLng      float64            `json:"check_in_lng"`
	CheckInAccuracy pgtype.Float8      `json:"check_in_accuracy"`
	CheckInTime     pgtype.Timestamptz `json:"check_in_time"`
	DistanceMeters  pgtype.Float8      `json:"distance_meters"`
	BusinessDate    pgtype.Date        `json:"business_date"`
	Notes           string             `json:"notes"`
	CancelledAt     pgtype.Timestamptz `json:"cancelled_at"`
	CancelledBy     pgtype.Int8        `json:"cancelled_by"`
	CancelReason    string             `json:"cancel_reason"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	SalesName       string             `json:"sales_name"`
	WarungName      string             `json:"warung_name"`
}

func (q *Queries) ListRecentVisits(ctx context.Context) ([]ListRecentVisitsRow, error) {
	rows, err := q.db.Query(ctx, listRecentVisits)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRecentVisitsRow{}
	for rows.Next() {
		var i ListRecentVisitsRow
		if err := rows.Scan(
			&i.ID,
			&i.SalesID,
			&i.WarungID,
			&i.Status,
			&i.CheckInLat,
			&i.CheckInLng,
			&i.CheckInAccuracy,
			&i.CheckInTime,
			&i.DistanceMeters,
			&i.BusinessDate,
			&i.Notes,
			&i.CancelledAt,
			&i.CancelledBy,
			&i.CancelReason,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SalesName,
			&i.WarungName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVisitsBySales = `-- name: ListVisitsBySales :many
SELECT id, sales_id, warung_id, status, check_in_lat, check_in_lng, check_in_accuracy, check_in_time, distance_meters, business_date, notes, cancelled_at, cancelled_by, cancel_reason, created_at, updated_at
FROM visits
WHERE sales_id = $1
ORDER BY created_at DESC
LIMIT 50
`

func (q *Queries) ListVisitsBySales(ctx context.Context, salesID int64) ([]Visit, error) {
	rows, err := q.db.Query(ctx, listVisitsBySales, salesID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Visit{}
	for rows.Next() {
		var i Visit
		if err := rows.Scan(
			&i.ID,
			&i.SalesID,
			&i.WarungID,
			&i.Status,
			&i.CheckInLat,
			&i.CheckInLng,
			&i.CheckInAccuracy,
			&i.CheckInTime,
			&i.DistanceMeters,
			&i.BusinessDate,
			&i.Notes,
			&i.CancelledAt,
			&i.CancelledBy,
			&i.CancelReason,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVisitsBySalesAndDate = `-- name: ListVisitsBySalesAndDate :many
SELECT id, sales_id, warung_id, status, check_in_lat, check_in_lng, check_in_accuracy, check_in_time, distance_meters, business_date, notes, cancelled_at, cancelled_by, cancel_reason, created_at, updated_at
FROM visits
WHERE sales_id = $1 AND business_date >= $2 AND business_date <= $3
ORDER BY created_at DESC
`

type ListVisitsBySalesAndDateParams struct {
	SalesID        int64       `json:"sales_id"`
	BusinessDate   pgtype.Date `json:"business_date"`
	BusinessDate_2 pgtype.Date `json:"business_date_2"`
}

func (q *Queries) ListVisitsBySalesAndDate(ctx context.Context, arg ListVisitsBySalesAndDateParams) ([]Visit, error) {
	rows, err := q.db.Query(ctx, listVisitsBySalesAndDate, arg.SalesID, arg.BusinessDate, arg.BusinessDate_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Visit{}
	for rows.Next() {
		var i Visit
		if err := rows.Scan(
			&i.ID,
			&i.SalesID,
			&i.WarungID,
			&i.Status,
			&i.CheckInLat,
			&i.CheckInLng,
			&i.CheckInAccuracy,
			&i.CheckInTime,
			&i.DistanceMeters,
			&i.BusinessDate,
			&i.Notes,
			&i.CancelledAt,
			&i.CancelledBy,
			&i.CancelReason,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVisitsByWarung = `-- name: ListVisitsByWarung :many
SELECT id, sales_id, warung_id, status, check_in_lat, check_in_lng, check_in_accuracy, check_in_time, distance_meters, business_date, notes, cancelled_at, cancelled_by, cancel_reason, created_at, updated_at
FROM visits
WHERE warung_id = $1 AND status = 'selesai'
ORDER BY business_date, created_at
`

func (q *Queries) ListVisitsByWarung(ctx context.Context, warungID int64) ([]Visit, error) {
	rows, err := q.db.Query(ctx, listVisitsByWarung, warungID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Visit{}
	for rows.Next() {
		var i Visit
		if err := rows.Scan(
			&i.ID,
			&i.SalesID,
			&i.WarungID,
			&i.Status,
			&i.CheckInLat,
			&i.CheckInLng,
			&i.CheckInAccuracy,
			&i.CheckInTime,
			&i.DistanceMeters,
			&i.BusinessDate,
			&i.Notes,
			&i.CancelledAt,
			&i.CancelledBy,
			&i.CancelReason,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateVisitDistance = `-- name: UpdateVisitDistance :exec
UPDATE visits
SET distance_meters = $2
WHERE id = $1
`

type UpdateVisitDistanceParams struct {
	ID             int64         `json:"id"`
	DistanceMeters pgtype.Float8 `json:"distance_meters"`
}

func (q *Queries) UpdateVisitDistance(ctx context.Context, arg UpdateVisitDistanceParams) error {
	_, err := q.db.Exec(ctx, updateVisitDistance, arg.ID, arg.DistanceMeters)
	return err
}

const updateVisitStatus = `-- name: UpdateVisitStatus :exec
UPDATE visits
SET status = $2, updated_at = NOW()
WHERE id = $1
`

type UpdateVisitStatusParams struct {
	ID     int64  `json:"id"`
	Status string `json:"status"`
}

func (q *Queries) UpdateVisitStatus(ctx context.Context, arg UpdateVisitStatusParams) error {
	_, err := q.db.Exec(ctx, updateVisitStatus, arg.ID, arg.Status)
	return err
}
