// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: warungs.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countWarungs = `-- name: CountWarungs :one
SELECT COUNT(*)::bigint FROM warungs WHERE active = TRUE
`

func (q *Queries) CountWarungs(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countWarungs)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createWarung = `-- name: CreateWarung :one
INSERT INTO warungs (name, owner_name, phone, address, latitude, longitude, created_by, acquired_from_checkin)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, name, owner_name, phone, address, latitude, longitude, active, created_by, acquired_from_checkin, created_at, updated_at
`

type CreateWarungParams struct {
	Name                string        `json:"name"`
	OwnerName           string        `json:"owner_name"`
	Phone               string        `json:"phone"`
	Address             string        `json:"address"`
	Latitude            pgtype.Float8 `json:"latitude"`
	Longitude           pgtype.Float8 `json:"longitude"`
	CreatedBy           int64         `json:"created_by"`
	AcquiredFromCheckin bool          `json:"acquired_from_checkin"`
}

func (q *Queries) CreateWarung(ctx context.Context, arg CreateWarungParams) (Warung, error) {
	row := q.db.QueryRow(ctx, createWarung,
		arg.Name,
		arg.OwnerName,
		arg.Phone,
		arg.Address,
		arg.Latitude,
		arg.Longitude,
		arg.CreatedBy,
		arg.AcquiredFromCheckin,
	)
	var i Warung
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerName,
		&i.Phone,
		&i.Address,
		&i.Latitude,
		&i.Longitude,
		&i.Active,
		&i.CreatedBy,
		&i.AcquiredFromCheckin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deactivateWarung = `-- name: DeactivateWarung :exec
UPDATE warungs
SET active = FALSE, updated_at = NOW()
WHERE id = $1
`

func (q *Queries) DeactivateWarung(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deactivateWarung, id)
	return err
}

const findDuplicateWarungs = `-- name: FindDuplicateWarungs :many
SELECT id, name, owner_name, phone, address, latitude, longitude, active, created_by, created_at, updated_at
FROM warungs
WHERE LOWER(name) = LOWER($1) AND active = TRUE AND id != $2
LIMIT 10
`

type FindDuplicateWarungsParams struct {
	Lower string `json:"lower"`
	ID    int64  `json:"id"`
}

type FindDuplicateWarungsRow struct {
	ID        int64              `json:"id"`
	Name      string             `json:"name"`
	OwnerName string             `json:"owner_name"`
	Phone     string             `json:"phone"`
	Address   string             `json:"address"`
	Latitude  pgtype.Float8      `json:"latitude"`
	Longitude pgtype.Float8      `json:"longitude"`
	Active    bool               `json:"active"`
	CreatedBy int64              `json:"created_by"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) FindDuplicateWarungs(ctx context.Context, arg FindDuplicateWarungsParams) ([]FindDuplicateWarungsRow, error) {
	rows, err := q.db.Query(ctx, findDuplicateWarungs, arg.Lower, arg.ID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindDuplicateWarungsRow{}
	for rows.Next() {
		var i FindDuplicateWarungsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.OwnerName,
			&i.Phone,
			&i.Address,
			&i.Latitude,
			&i.Longitude,
			&i.Active,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findWarungByID = `-- name: FindWarungByID :one
SELECT id, name, owner_name, phone, address, latitude, longitude, active, created_by, acquired_from_checkin, created_at, updated_at
FROM warungs WHERE id = $1
`

func (q *Queries) FindWarungByID(ctx context.Context, id int64) (Warung, error) {
	row := q.db.QueryRow(ctx, findWarungByID, id)
	var i Warung
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerName,
		&i.Phone,
		&i.Address,
		&i.Latitude,
		&i.Longitude,
		&i.Active,
		&i.CreatedBy,
		&i.AcquiredFromCheckin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveWarungs = `-- name: ListActiveWarungs :many
SELECT id, name, owner_name, phone, address, latitude, longitude, active, created_by, acquired_from_checkin, created_at, updated_at
FROM warungs
WHERE active = TRUE
ORDER BY name
`

func (q *Queries) ListActiveWarungs(ctx context.Context) ([]Warung, error) {
	rows, err := q.db.Query(ctx, listActiveWarungs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Warung{}
	for rows.Next() {
		var i Warung
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.OwnerName,
			&i.Phone,
			&i.Address,
			&i.Latitude,
			&i.Longitude,
			&i.Active,
			&i.CreatedBy,
			&i.AcquiredFromCheckin,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWarungs = `-- name: ListWarungs :many
SELECT id, name, owner_name, phone, address, latitude, longitude, active, created_by, acquired_from_checkin, created_at, updated_at
FROM warungs
ORDER BY active DESC, name
`

func (q *Queries) ListWarungs(ctx context.Context) ([]Warung, error) {
	rows, err := q.db.Query(ctx, listWarungs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Warung{}
	for rows.Next() {
		var i Warung
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.OwnerName,
			&i.Phone,
			&i.Address,
			&i.Latitude,
			&i.Longitude,
			&i.Active,
			&i.CreatedBy,
			&i.AcquiredFromCheckin,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchWarungs = `-- name: SearchWarungs :many
SELECT id, name, owner_name, phone, address, latitude, longitude, active, created_by, acquired_from_checkin, created_at, updated_at
FROM warungs
WHERE active = TRUE AND (LOWER(name) LIKE LOWER('%' || $1 || '%') OR LOWER(address) LIKE LOWER('%' || $1 || '%'))
ORDER BY name
LIMIT 50
`

func (q *Queries) SearchWarungs(ctx context.Context, dollar_1 pgtype.Text) ([]Warung, error) {
	rows, err := q.db.Query(ctx, searchWarungs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Warung{}
	for rows.Next() {
		var i Warung
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.OwnerName,
			&i.Phone,
			&i.Address,
			&i.Latitude,
			&i.Longitude,
			&i.Active,
			&i.CreatedBy,
			&i.AcquiredFromCheckin,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWarung = `-- name: UpdateWarung :exec
UPDATE warungs
SET name = COALESCE($2, name),
    owner_name = COALESCE($3, owner_name),
    phone = COALESCE($4, phone),
    address = COALESCE($5, address),
    latitude = COALESCE($6, latitude),
    longitude = COALESCE($7, longitude),
    updated_at = NOW()
WHERE id = $1
`

type UpdateWarungParams struct {
	ID        int64         `json:"id"`
	Name      string        `json:"name"`
	OwnerName string        `json:"owner_name"`
	Phone     string        `json:"phone"`
	Address   string        `json:"address"`
	Latitude  pgtype.Float8 `json:"latitude"`
	Longitude pgtype.Float8 `json:"longitude"`
}

func (q *Queries) UpdateWarung(ctx context.Context, arg UpdateWarungParams) error {
	_, err := q.db.Exec(ctx, updateWarung,
		arg.ID,
		arg.Name,
		arg.OwnerName,
		arg.Phone,
		arg.Address,
		arg.Latitude,
		arg.Longitude,
	)
	return err
}

const updateWarungGPS = `-- name: UpdateWarungGPS :exec
UPDATE warungs
SET latitude = $2, longitude = $3, updated_at = NOW()
WHERE id = $1
`

type UpdateWarungGPSParams struct {
	ID        int64         `json:"id"`
	Latitude  pgtype.Float8 `json:"latitude"`
	Longitude pgtype.Float8 `json:"longitude"`
}

func (q *Queries) UpdateWarungGPS(ctx context.Context, arg UpdateWarungGPSParams) error {
	_, err := q.db.Exec(ctx, updateWarungGPS, arg.ID, arg.Latitude, arg.Longitude)
	return err
}
